name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  commons:
    path: ../commons
  sqflite: ^2.0.2+1
  http_interceptor: ^1.0.2
  path: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

flutter:
  module:
    androidX: true
    androidPackage: esser.marcelo.univesity.loader.core
    iosBundleIdentifier: esser.marcelo.univesity.loader.core
